name: Not3s
description: A TO-DO app bundled with some functionalites of a Notes app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7+3
  flare_flutter: ^2.0.3
  page_transition: ^1.1.5
  flushbar: ^1.10.4
  provider: ^4.1.3
  eva_icons_flutter: ^2.0.0
  image_picker_saver: ^0.3.0
  intl: ^0.16.1
  flui: ^0.9.2
  after_layout: ^1.0.7+2
  flutter_local_notifications: ^1.4.4+2
  path_provider: ^1.6.11
  uuid: ^2.2.0
  flutter_app_badger: ^1.1.2
  keyboard_attachable: ^1.0.3
  speech_to_text: ^2.3.0
  image_cropper: ^1.2.3
  colorful_safe_area: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  anroid: true
  image_path: "assets/images/appIcon1.png"

flutter_native_splash:
  image: assets/images/appIcon.png
  color: ffffff

flutter:
  uses-material-design: true

  assets:
    - assets/flare/empty2.flr
    - assets/flare/error.flr
    - assets/flare/success.flr
    - assets/images/appIcon1.png
    - assets/images/appIcon.png
